const categoryImages={
 'Bildungslücke':'bildungsluecke.png','Boulevard':'boulevard.png','Der Mensch':'der-mensch.png','Essen & Trinken':'essen-trinken.png','Heiße Kartoffel':'heisse-kartoffel.png','In der Natur':'in-der-natur.png','Kultur & Geschichte':'kultur-geschichte.png','Medien & Unterhaltung':'medien-unterhaltung.png','Typisch Deutsch':'typisch-deutsch.png','Um den Globus':'um-den-globus.png','Wenn nicht jetzt, wann dann?':'wenn-nicht-jetzt.png','Wer bin Ich':'wer-bin-ich.png','Wissenschaft & Technik':'wissenschaft-technik.png','Religion & Glaube':'religion-glaube.png'
};
let S={players:[],rounds:1,round:1,current:0,playsThisTurn:0,questions:[],cards:[],currentQ:null,selectedCard:null,log:[],usedQuestionIds:[],categoryCounts:{},phase:'home',ui:null};
let ONLINE=false, DB=null, ROOM=null, MY_ID=localStorage.getItem('quizpoker_my_id')||crypto.randomUUID(), IS_HOST=false, REMOTE=false, UNSUB=null;
localStorage.setItem('quizpoker_my_id',MY_ID);
const app=document.getElementById('app');
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const rand=a=>a[Math.floor(Math.random()*a.length)];
const norm=x=>String(x||'').trim().toLowerCase().replace(/[.!?]/g,'');
function log(t){S.log.unshift(t)}
function score(i,n){if(!S.players[i])return;S.players[i].score+=n;log(`${S.players[i].name}: ${n>0?'+':''}${n} Punkt(e)`)}
function weightedRand(items){const total=items.reduce((s,i)=>s+(+i.weight||1),0);let r=Math.random()*total;for(const i of items){r-=+i.weight||1;if(r<=0)return i}return items[items.length-1]}
function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/&/g,'und').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function myIndex(){return S.players.findIndex(p=>p.id===MY_ID)}
function isMe(i){return !ONLINE || myIndex()===i}
function isActiveMe(){return isMe(S.current)}
function canHost(){return !ONLINE || myIndex()===S.current}
function active(){return S.players[S.current]||{name:'—'}}
function firebaseConfigured(){const f=window.QUIZPOKER_FIREBASE;return !!(f&&f.firebaseEnabled&&f.config&&f.config.apiKey&&!String(f.config.apiKey).includes('DEIN_'))}
function initFirebase(){if(!firebaseConfigured())return false;try{if(!firebase.apps.length)firebase.initializeApp(window.QUIZPOKER_FIREBASE.config);DB=firebase.firestore();return true}catch(e){console.error(e);return false}}
function roomRef(code=ROOM){return DB.collection('quizpoker_rooms').doc(String(code).toUpperCase())}
function roomCode(){return Math.random().toString(36).slice(2,6).toUpperCase()}
async function saveRoom(status='playing'){if(!ONLINE||!DB||!ROOM||REMOTE)return;await roomRef().set({status,state:S,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}
async function init(){try{S.questions=await fetch('questions.json').then(r=>r.json());S.cards=await fetch('cards.json').then(r=>r.json())}catch(e){S.questions=window.QUIZPOKER_QUESTIONS||[];S.cards=window.QUIZPOKER_CARDS||[]}
S.questions=normalizeQuestions(S.questions);if(!S.questions.length||!S.cards.length){app.innerHTML='<div class="wrap"><section class="panel"><h1>Quizpoker</h1><p>Daten konnten nicht geladen werden.</p></section></div>';return}renderHome()}
function normalizeQuestions(list){return(list||[]).map(q=>{q={...q};const c=`${q.category||''} ${q.question||''} ${q.correct||''} ${q.answer||''}`.toLowerCase();if(q.type!=='schaetzfrage'&&/(schätz|schaetz|schätzen|schaetzen)/i.test(c))q.type='schaetzfrage';if(q.category==='Wenn nicht jetzt, wann dann?')q.type='schaetzfrage';return q})}
function isSpecial(q){return ['wer_bin_ich','heisse_kartoffel','schaetzfrage'].includes(q&&q.type)}
function noSpecial(q){return !isSpecial(q)}
function playerChecks(name,exclude=true){return S.players.map((p,i)=>exclude&&i===S.current?'':`<label class="check"><input type="checkbox" name="${name}" value="${i}"> ${p.name}</label>`).join('')}
function checked(name){return $$(`input[name="${name}"]:checked`).map(x=>+x.value)}
function renderHome(){const ready=initFirebase();app.innerHTML=`<div class="wrap"><section class="hero"><h1>Quizpoker</h1><p>Multiplayer v09 mit sauberem Tipp-/Antwortmodus.</p></section><section class="panel"><h2>Start</h2><div class="row"><div class="field"><h3>Lokal testen</h3><button id="local">Lokales Spiel starten</button></div><div class="field"><h3>Multiplayer</h3>${ready?`<label>Dein Name</label><input id="onlineName" placeholder="Name"><label>Raumcode</label><input id="roomCode" placeholder="z. B. ABCD"><button id="createRoom">Raum erstellen</button> <button class="secondary" id="joinRoom">Raum beitreten</button>`:`<p class="muted">Firebase ist noch nicht aktiviert.</p>`}</div></div></section></div>`;$('#local').onclick=()=>renderSetup();if(ready){$('#createRoom').onclick=createOnlineRoom;$('#joinRoom').onclick=joinOnlineRoom}}
async function createOnlineRoom(){const name=$('#onlineName').value.trim();if(!name)return alert('Bitte Namen eintragen.');ROOM=roomCode();IS_HOST=true;ONLINE=true;await roomRef().set({status:'lobby',hostId:MY_ID,rounds:1,players:[{id:MY_ID,name,score:0}],createdAt:firebase.firestore.FieldValue.serverTimestamp()});watchRoom()}
async function joinOnlineRoom(){const name=$('#onlineName').value.trim(),rc=$('#roomCode').value.trim().toUpperCase();if(!name||!rc)return alert('Bitte Name und Raumcode eintragen.');ROOM=rc;ONLINE=true;IS_HOST=false;const ref=roomRef(),snap=await ref.get();if(!snap.exists)return alert('Raum nicht gefunden.');const data=snap.data();const players=(data.players||[]).filter(p=>p.id!==MY_ID);players.push({id:MY_ID,name,score:0});await ref.update({players});watchRoom()}
function watchRoom(){if(UNSUB)UNSUB();UNSUB=roomRef().onSnapshot(snap=>{if(!snap.exists)return;const data=snap.data();if(data.status==='lobby')renderOnlineLobby(data);if(data.state){REMOTE=true;S=data.state;REMOTE=false;if(data.status==='ended')endGame(false);else renderGame()}})}
function renderOnlineLobby(data){app.innerHTML=`<div class="wrap"><section class="hero"><h1>Quizpoker</h1><p>Raumcode: <b class="big">${ROOM}</b></p></section><section class="panel"><h2>Lobby</h2><p>${IS_HOST?'Du bist Spielleiter.':'Warte, bis der Spielleiter startet.'}</p>${(data.players||[]).map(p=>`<div class="score"><span>${p.name}</span><b>bereit</b></div>`).join('')}${IS_HOST?`<label>Rundenanzahl</label><input id="roundsOnline" type="number" min="1" value="${data.rounds||1}"><button id="startOnline">Spiel starten</button>`:''}</section></div>`;if(IS_HOST)$('#startOnline').onclick=()=>startOnlineGame(data.players||[])}
async function startOnlineGame(players){if(players.length<2)return alert('Bitte mindestens 2 Spieler.');S.players=players.map(p=>({id:p.id,name:p.name,score:0,hand:drawHand(5)}));S.usedQuestionIds=[];S.categoryCounts={};S.rounds=Math.max(1,parseInt($('#roundsOnline').value||1));S.round=1;S.current=0;S.playsThisTurn=0;S.log=[];S.phase='choose_card';S.ui=null;log('Multiplayer-Spiel gestartet.');drawQuestion();await roomRef().set({status:'playing',state:S},{merge:true})}
function renderSetup(){app.innerHTML=`<div class="wrap"><section class="hero"><h1>Quizpoker</h1></section><section class="panel"><div class="row"><div class="field"><label>Spieler, jeweils eine Zeile</label><textarea id="names" rows="6">Erik\nLisa\nTom</textarea></div><div class="field"><label>Rundenanzahl</label><input id="rounds" type="number" min="1" value="1"><button id="start">Spiel starten</button></div></div></section></div>`;$('#start').onclick=()=>{ONLINE=false;const names=$('#names').value.split('\n').map(x=>x.trim()).filter(Boolean);if(names.length<2)return alert('Bitte mindestens 2 Spieler.');S.players=names.map((n,i)=>({id:'local'+i,name:n,score:0,hand:drawHand(5)}));S.usedQuestionIds=[];S.categoryCounts={};S.rounds=Math.max(1,parseInt($('#rounds').value||1));S.round=1;S.current=0;S.playsThisTurn=0;S.log=[];S.phase='choose_card';drawQuestion();renderGame()}}
function drawCardForHand(hand=[]){
  for(let tries=0;tries<80;tries++){
    const card=weightedRand(S.cards);
    const count=hand.filter(c=>c.id===card.id).length;
    if(count<3)return card;
  }
  return weightedRand(S.cards);
}
function drawHand(n){const hand=[];while(hand.length<n)hand.push(drawCardForHand(hand));return hand}
function refillHand(i){while(S.players[i].hand.length<5)S.players[i].hand.push(drawCardForHand(S.players[i].hand))}
function drawQuestion(category=null,excludeSpecial=false){S.currentQ=takeQuestion(category,excludeSpecial);S.selectedCard=null}
function takeQuestion(category=null,excludeSpecial=false){let pool=S.questions.filter(q=>(!category||q.category===category)&&!S.usedQuestionIds.includes(q.id));if(excludeSpecial)pool=pool.filter(noSpecial);if(!pool.length){pool=S.questions.filter(q=>(!category||q.category===category));if(excludeSpecial)pool=pool.filter(noSpecial)}if(!pool.length)pool=S.questions.filter(q=>!S.usedQuestionIds.includes(q.id));if(!pool.length){S.usedQuestionIds=[];pool=S.questions.slice();log('Der Fragenstapel wurde neu gemischt.')}let q=category?rand(pool):takeBalancedByCategory(pool);if(q&&q.id&&!S.usedQuestionIds.includes(q.id))S.usedQuestionIds.push(q.id);if(q&&q.category)S.categoryCounts[q.category]=(S.categoryCounts[q.category]||0)+1;return q}
function takeBalancedByCategory(pool){const cats=[...new Set(pool.map(q=>q.category))];const min=Math.min(...cats.map(c=>S.categoryCounts[c]||0));const pick=rand(cats.filter(c=>(S.categoryCounts[c]||0)===min));return rand(pool.filter(q=>q.category===pick))}
function shell(center=''){app.innerHTML=`<div class="wrap"><div class="layout"><aside class="panel"><h2>Punkte</h2>${S.players.map((p,i)=>`<div class="score ${i===S.current?'active':''}"><span>${p.name}${ONLINE&&p.id===MY_ID?' (du)':''}</span><b>${p.score}</b></div>`).join('')}<p><span class="pill">Runde ${S.round}/${S.rounds}</span><span class="pill">${active().name} ist dran</span>${ONLINE?`<span class="pill">Raum ${ROOM}</span>`:''}<span class="pill">Aktion ${S.playsThisTurn+1}/3</span></p></aside><section>${center}</section><aside class="panel"><h2>Protokoll</h2><div class="log">${S.log.map(x=>`<div>${x}</div>`).join('')}</div></aside></div></div>`}
function publicQuestion(q){return `<div class="question"><div class="pill">${q.category}</div><h2>${q.question}</h2></div>`}
function answerButtons(q,disabled=false){if(q.answers&&q.answers.length)return `<div class="answers">${q.answers.map(a=>`<button class="ans" data-a="${a}" ${disabled?'disabled':''}>${a}</button>`).join('')}</div>`;return disabled?`<p class="muted">Freitextantwort verborgen.</p>`:`<input id="free" placeholder="Antwort eintippen"><button id="show">Antwort abgeben</button>`}
function renderGame(){if(!S.currentQ)drawQuestion();if(isSpecial(S.currentQ))return renderSpecial();if(S.phase==='answer')return renderAnswer();if(S.phase==='reveal')return renderReveal();if(S.phase==='choose_target')return renderChooseTarget();if(S.phase==='group_predict'||S.phase==='group_answer'||S.phase==='group_reveal')return renderGroup();renderChooseCard()}
function renderChooseCard(){const q=S.currentQ,img=categoryImages[q.category]||`${slug(q.category)}.png`;const activeTurn=isActiveMe();shell(`<div class="panel center"><h2>Gezogene Quizkarte</h2><div class="category-card draw-anim"><img class="card-img" src="${img}" onerror="this.style.display='none'"></div><p class="big">${q.category}</p>${activeTurn?`<p>Spiele eine Handkarte aus.</p><div class="hand">${active().hand.map((c,i)=>`<button class="mini hand-anim" style="animation-delay:${i*70}ms" data-i="${i}"><img src="${c.image}"><b>${c.name}</b></button>`).join('')}</div>`:`<p class="muted">Warte, bis ${active().name} eine Handkarte spielt.</p>`}</div>`);if(activeTurn)$$('.mini').forEach(b=>b.onclick=()=>playCard(+b.dataset.i))}
function playCard(i){S.selectedCard=active().hand[i];active().hand.splice(i,1);log(`${active().name} spielt „${S.selectedCard.name}“.`);const id=S.selectedCard.id;if(id==='ich_bin_dran')startAnswer(S.current,null,null);else if(id==='du_bist_dran'||id==='fragenhagel'||id==='direktes_duell'){S.phase='choose_target';S.ui={cardId:id};renderGame();saveRoom()}else if(id==='ihr_seid_dran'){S.phase='group_predict';S.ui={};renderGame();saveRoom()}}
function renderChooseTarget(){const id=S.ui.cardId;let title=id==='du_bist_dran'?'Wer soll antworten?':id==='fragenhagel'?'Wer bekommt den Fragenhagel?':'Gegen wen duellierst du dich?';if(!isActiveMe())return shell(`<div class="panel center"><h2>${title}</h2><p class="muted">Warte auf ${active().name}.</p></div>`);const buttons=S.players.map((p,i)=>{if(id!=='fragenhagel'&&i===S.current)return '';return `<button class="target" data-i="${i}">${p.name}</button>`}).join(' ');shell(`<div class="panel"><h2>${title}</h2>${buttons}<div id="pred" style="margin-top:15px"></div></div>`);$$('.target').forEach(b=>b.onclick=()=>{const t=+b.dataset.i;if(id==='du_bist_dran'){$('#pred').innerHTML=`<h3>Einschätzung</h3><button id="pr">${S.players[t].name} liegt richtig</button> <button id="pf">${S.players[t].name} liegt falsch</button>`;$('#pr').onclick=()=>startAnswer(t,S.current,'richtig');$('#pf').onclick=()=>startAnswer(t,S.current,'falsch')}else if(id==='fragenhagel')startSeries('fragenhagel',t);else startSeries('duell',t)})}
function startAnswer(playerIndex,predictor=null,pred=null,q=S.currentQ,after=null){S.phase='answer';S.ui={playerIndex,predictor,pred,q,after};renderGame();saveRoom()}
function renderAnswer(){const u=S.ui,q=u.q||S.currentQ,answerer=u.playerIndex;const allowed=isMe(answerer);const viewer=allowed?answerButtons(q):((q.answers&&q.answers.length)?answerButtons(q,true):`<p class="muted">Warte auf die Antwort von ${S.players[answerer].name}.</p>`);shell(`<div class="panel"><h2>${S.players[answerer].name} antwortet</h2>${publicQuestion(q)}${viewer}<div id="result"></div></div>`);if(!allowed)return;if(q.answers&&q.answers.length)$$('.ans').forEach(b=>b.onclick=()=>submitAnswer(norm(b.dataset.a)===norm(q.correct),b.dataset.a));else $('#show').onclick=()=>submitAnswer(null,$('#free').value||'—')}
function submitAnswer(correct,given){const q=S.ui.q||S.currentQ;if(correct===null){S.phase='reveal';S.ui={...S.ui,given,needsJudge:true};}else{S.phase='reveal';S.ui={...S.ui,given,correct,needsJudge:false};}renderGame();saveRoom()}
function renderReveal(){const u=S.ui,q=u.q||S.currentQ;const judge=canHost();const answerer=isMe(u.playerIndex);if(!judge&&!answerer)return shell(`<div class="panel center"><h2>Antwort abgegeben</h2><p class="muted">Warte auf ${active().name}, ohne dass die Lösung angezeigt wird.</p></div>`);shell(`<div class="panel"><h2>Auflösung</h2>${publicQuestion(q)}<p>Gegebene Antwort: <b>${u.given||'—'}</b></p><p>Richtige Antwort: <b>${q.correct||q.solution}</b></p>${u.needsJudge?(judge?`<button id="right">Richtig</button> <button class="secondary" id="wrong">Falsch</button>`:`<p class="muted">Warte auf Bewertung durch ${active().name}.</p>`):(judge?`<button id="next">Weiter</button>`:`<p class="muted">Warte auf Weiter.</p>`)}</div>`);if(!judge)return;if(u.needsJudge){$('#right').onclick=()=>finishAnswer(true);$('#wrong').onclick=()=>finishAnswer(false)}else $('#next').onclick=()=>finishAnswer(u.correct)}
function finishAnswer(correct){const u=S.ui;if(u.after)return finishSeries(correct);if(correct)score(u.playerIndex,1);if(u.predictor!==null&&u.predictor!==undefined){if((correct?'richtig':'falsch')===u.pred)score(u.predictor,1)}nextAction()}
function renderGroup(){if(S.phase==='group_predict'){if(!isActiveMe())return shell(`<div class="panel center"><h2>Mehrheit einschätzen</h2><p class="muted">Warte auf ${active().name}.</p></div>`);shell(`<div class="panel"><h2>Mehrheit einschätzen</h2><p>Glaubst du, die Mehrheit der anderen liegt richtig oder falsch?</p><button id="mr">Mehrheit richtig</button> <button id="mf">Mehrheit falsch</button></div>`);$('#mr').onclick=()=>{S.phase='group_answer';S.ui={pred:'richtig',results:{}};renderGame();saveRoom()};$('#mf').onclick=()=>{S.phase='group_answer';S.ui={pred:'falsch',results:{}};renderGame();saveRoom()};return}
const q=S.currentQ,u=S.ui,idx=myIndex();if(S.phase==='group_answer'){const must=idx!==S.current&&idx>=0;const done=must&&u.results&&u.results[idx]!==undefined;shell(`<div class="panel"><h2>Alle anderen antworten</h2>${publicQuestion(q)}${must&&!done?answerButtons(q):`<p class="muted">${must?'Antwort gespeichert.':'Warte auf die anderen Spieler.'}</p>`}<p>${Object.keys(u.results||{}).length}/${S.players.length-1} Antworten erhalten.</p>${canHost()?`<button id="force">Auswerten</button>`:''}<div id="result"></div></div>`);if(must&&!done){if(q.answers&&q.answers.length)$$('.ans').forEach(b=>b.onclick=()=>{u.results[idx]=norm(b.dataset.a)===norm(q.correct);renderGame();saveRoom()});else $('#show').onclick=()=>{u.results[idx]=confirm(`Richtige Antwort: ${q.correct}\nWar deine Antwort richtig?`);renderGame();saveRoom()}}if(canHost())$('#force').onclick=finishGroup;if(Object.keys(u.results||{}).length>=S.players.length-1&&canHost())finishGroup();return}}
function finishGroup(){const vals=Object.values(S.ui.results||{});const corrects=vals.filter(Boolean).length;const majority=corrects>vals.length/2?'richtig':'falsch';if(majority===S.ui.pred)score(S.current,1);else S.players.forEach((p,i)=>{if(i!==S.current)score(i,1)});nextAction()}
function startSeries(kind,target){const cat=S.currentQ.category;S.phase='answer';S.ui={series:{kind,target,idx:0,a:0,b:0,qs:[takeQuestion(cat,true),takeQuestion(cat,true),takeQuestion(cat,true)]},playerIndex:kind==='fragenhagel'?target:S.current,q:null,after:kind};S.ui.q=S.ui.series.qs[0];renderGame();saveRoom()}
function finishSeries(correct){const ser=S.ui.series;if(ser.kind==='fragenhagel'){if(correct)score(ser.target,1);else score(ser.target,-1);ser.idx++;if(ser.idx>=3)return nextAction();S.ui={series:ser,playerIndex:ser.target,q:ser.qs[ser.idx],after:'fragenhagel'};S.phase='answer';renderGame();saveRoom();return}
if(ser.kind==='duell'){if(S.ui.playerIndex===S.current){if(correct)ser.a++;S.ui={series:ser,playerIndex:ser.target,q:ser.qs[ser.idx],after:'duell'};S.phase='answer';renderGame();saveRoom();return}else{if(correct)ser.b++;ser.idx++;if(ser.idx>=3){if(ser.a>ser.b){score(S.current,ser.a);score(ser.target,-(ser.a-ser.b))}else if(ser.b>ser.a){score(ser.target,ser.b);score(S.current,-(ser.b-ser.a))}else log('Duell endet unentschieden.');return nextAction()}S.ui={series:ser,playerIndex:S.current,q:ser.qs[ser.idx],after:'duell'};S.phase='answer';renderGame();saveRoom();return}}
}
function renderSpecial(){const q=S.currentQ;if(q.type==='heisse_kartoffel')return renderHotPotato(q);if(q.type==='wer_bin_ich')return renderWhoAmI(q);return renderEstimate(q)}
function selectOptionsWithNone(excludeCurrent=true){return `<option value="-1">Niemand</option>`+S.players.map((p,i)=>excludeCurrent&&i===S.current?'':`<option value="${i}">${p.name}</option>`).join('')}
function checksWithNone(name,excludeCurrent=true){return `<label class="check"><input type="checkbox" name="${name}" value="-1"> Niemand</label>`+S.players.map((p,i)=>excludeCurrent&&i===S.current?'':`<label class="check"><input type="checkbox" name="${name}" value="${i}"> ${p.name}</label>`).join('')}
function realPlayers(list){return list.filter(i=>i>=0)}
function renderHotPotato(q){
  if(!S.ui||S.ui.mode!=='hot')S.ui={mode:'hot',step:'predict',pred:null};
  const u=S.ui;
  if(u.step==='predict'){
    if(!isActiveMe())return shell(`<div class="panel center"><h2>Heiße Kartoffel</h2><p class="big">${q.topic}</p><p class="muted">Warte, bis ${active().name} den Tipp gespeichert hat.</p></div>`);
    shell(`<div class="panel"><h2>Heiße Kartoffel</h2><div class="question"><h2>${q.topic}</h2></div><p class="muted">Erst Tipp speichern, danach wird ausgewertet.</p><label>${active().name}s Tipp: Wer fliegt zuerst raus?</label><select id="pred">${selectOptionsWithNone(true)}</select><button id="savepred">Tipp speichern</button></div>`);
    $('#savepred').onclick=()=>{S.ui.pred=+$('#pred').value;S.ui.step='resolve';renderGame();saveRoom()};
    return;
  }
  if(!isActiveMe())return shell(`<div class="panel center"><h2>Heiße Kartoffel</h2><p class="big">${q.topic}</p><p class="muted">${active().name} wertet aus.</p></div>`);
  const predName=Number(u.pred)===-1?'Niemand':(S.players[Number(u.pred)]?.name||'—');
  shell(`<div class="panel"><h2>Heiße Kartoffel</h2><div class="question"><h2>${q.topic}</h2></div><p class="muted">Gespeicherter Tipp: <b>${predName}</b></p><label>Wer ist tatsächlich zuerst raus?</label><select id="out">${selectOptionsWithNone(true)}</select><button id="ok">Auswerten</button></div>`);
  $('#ok').onclick=()=>{let pred=Number(S.ui.pred),out=+$('#out').value;if(pred===out)score(S.current,1);if(out>=0)score(out,-1);nextAction()};
}
function renderWhoAmI(q){if(!S.ui||S.ui.mode!=='who')S.ui={mode:'who',step:'predict',clue:0,preds:[]};const u=S.ui;const clue=Number(u.clue)||0;const shown=q.clues.slice(0,clue).map((c,i)=>`<p><b>${i+1}.</b> ${c}</p>`).join('')||'<p>Noch keine Eigenschaft aufgedeckt.</p>';const pts=Math.max(1,6-Math.max(1,clue||1));if(!isActiveMe()){return shell(`<div class="panel center"><h2>Wer bin ich?</h2><div class="question">${shown}</div><p class="muted">${active().name} legt die Hinweise nacheinander auf.</p></div>`)}if(u.step==='predict'){shell(`<div class="panel"><h2>Wer bin ich?</h2><p>Lösung nur für ${active().name}: <b>${q.solution}</b></p><label>${active().name}s Tipp: Wer errät es?</label><div>${checksWithNone('pred',true)}</div><button id="savepred">Tipp speichern und starten</button></div>`);$('#savepred').onclick=()=>{S.ui.preds=checked('pred');S.ui.step='play';S.ui.clue=0;renderGame();saveRoom()};return}shell(`<div class="panel"><h2>Wer bin ich?</h2><p>Lösung nur für ${active().name}: <b>${q.solution}</b></p><p class="muted">Gespeicherter Tipp: ${realPlayers(u.preds||[]).map(i=>S.players[i].name).join(', ')||((u.preds||[]).includes(-1)?'Niemand':'—')}</p><div class="question" id="clues">${shown}</div><p class="muted">Aktuelle Punkte: <b>${pts}</b></p><button id="nextclue">Nächste Eigenschaft aufdecken</button><label>Wer hat es richtig erraten?</label><div>${checksWithNone('winner',true)}</div><button id="done">Auswerten</button></div>`);$('#nextclue').onclick=()=>{if(S.ui.clue<5)S.ui.clue++;renderGame();saveRoom()};$('#done').onclick=()=>{let winners=checked('winner'),preds=S.ui.preds||[];let realWinners=realPlayers(winners);let points=Math.max(1,6-Math.max(1,S.ui.clue||1));realWinners.forEach(w=>score(w,points));if((realWinners.length&&preds.some(p=>realWinners.includes(p)))||(!realWinners.length&&winners.includes(-1)&&preds.includes(-1)))score(S.current,points);nextAction()}}
function renderEstimate(q){
  if(!S.ui||S.ui.mode!=='estimate')S.ui={mode:'estimate',step:'predict',pred:null,answers:{}};
  const u=S.ui;
  const title=q.category==='Wenn nicht jetzt, wann dann?'?'Wenn nicht jetzt, wann dann?':'Schätzfrage';
  const idx=myIndex();
  if(u.step==='predict'){
    if(!isActiveMe())return shell(`<div class="panel center"><h2>${title}</h2><div class="question"><h2>${q.question}</h2></div><p class="muted">Warte, bis ${active().name} den Tipp gespeichert hat. Die Antwort bleibt verborgen.</p></div>`);
    shell(`<div class="panel"><h2>${title}</h2><div class="question"><h2>${q.question}</h2></div><p class="muted">Erst Tipp speichern, danach dürfen die anderen Spieler Antworten einreichen.</p><label>${active().name}s Tipp: Wer liegt richtig oder am nächsten dran?</label><select id="pred">${selectOptionsWithNone(true)}</select><button id="startEstimate">Tipp speichern und Antwortphase starten</button></div>`);
    $('#startEstimate').onclick=()=>{S.ui.pred=+$('#pred').value;S.ui.step='collect';S.ui.answers={};renderGame();saveRoom()};
    return;
  }
  if(u.step==='collect'){
    const isOther=idx>=0&&idx!==S.current;
    const hasAnswered=isOther&&u.answers&&u.answers[idx]!==undefined;
    if(!isActiveMe()){
      shell(`<div class="panel"><h2>${title}</h2><div class="question"><h2>${q.question}</h2></div>${isOther&&!hasAnswered?`<input id="estimateAnswer" placeholder="Deine Schätzung/Antwort"><button id="submitEstimate">Antwort einreichen</button>`:`<p class="muted">${hasAnswered?'Antwort eingereicht.':'Warte auf die Auswertung.'}</p>`}</div>`);
      if(isOther&&!hasAnswered)$('#submitEstimate').onclick=()=>{S.ui.answers[idx]=$('#estimateAnswer').value||'—';renderGame();saveRoom()};
      return;
    }
    const predName=Number(u.pred)===-1?'Niemand':(S.players[Number(u.pred)]?.name||'—');
    const entries=Object.entries(u.answers||{}).map(([i,a])=>`<div class="score"><span>${S.players[i]?.name||i}</span><b>${a}</b></div>`).join('')||'<p class="muted">Noch keine Antworten eingereicht.</p>';
    shell(`<div class="panel"><h2>${title}</h2><div class="question"><h2>${q.question}</h2><p>Antwort: <b>${q.correct}</b></p></div><p class="muted">Gespeicherter Tipp: <b>${predName}</b></p><h3>Eingereichte Antworten</h3>${entries}<p>${Object.keys(u.answers||{}).length}/${S.players.length-1} Antworten erhalten.</p><label>Wer lag richtig oder gleich nah dran?</label><div>${checksWithNone('winner',true)}</div><button id="ok">Auswerten</button></div>`);
    $('#ok').onclick=()=>{let pred=Number(S.ui.pred),winners=checked('winner'),realWinners=realPlayers(winners);if((realWinners.length&&realWinners.includes(pred))||(!realWinners.length&&winners.includes(-1)&&pred===-1)){score(S.current,1);realWinners.forEach(i=>score(i,1))}else realWinners.forEach(i=>score(i,2));nextAction()};
    return;
  }
}
function nextAction(){S.playsThisTurn++;if(S.playsThisTurn>=3){const f=S.current;refillHand(f);log(`${S.players[f].name} zieht auf 5 Handkarten nach.`);S.playsThisTurn=0;S.current++;if(S.current>=S.players.length){S.current=0;S.round++}}if(S.round>S.rounds)return endGame();drawQuestion();S.phase='choose_card';S.ui=null;saveRoom();renderGame()}
function endGame(save=true){if(save)saveRoom('ended');let max=Math.max(...S.players.map(p=>p.score)),winners=S.players.filter(p=>p.score===max);shell(`<div class="panel center"><h1>Spielende</h1>${S.players.slice().sort((a,b)=>b.score-a.score).map((p,i)=>`<p class="big">${i+1}. ${p.name}: ${p.score}</p>`).join('')}${winners.length>1?`<p>Gleichstand: Stichfrage nötig zwischen ${winners.map(w=>w.name).join(', ')}.</p>`:`<h2>Gewonnen hat ${winners[0].name}!</h2>`}<button onclick="location.reload()">Neues Spiel</button></div>`)}
init();
